<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=0"/>

    <?= $head ?? ""; ?>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/bootstrap/dist/css/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?= asset(CONF_PACK_NODE . "/@fortawesome/fontawesome-free/css/all.min.css"); ?>">

    <link rel="stylesheet" href="<?= theme("/assets/style.css", CONF_VIEW_APP);?>">

    <?= $v->section("css"); ?>
</head>
</html>

<body class="bg-light">

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Interface Homem Máquina</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </header>

  <main class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="d-flex flex-column flex-shrink-0 p-3">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
              <span class="fs-4">IHM</span>
            </a>
            <hr>
            <ul class="main-menu nav nav-pills flex-column mb-auto">
              <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page" id="menu_home" onclick="activeMenu('home')">
                  Home
                </a>
              </li>
              <li>
                <a href="#" class="nav-link" id="menu_soccer" onclick="activeMenu('soccer')">
                  Futebol
                </a>
              </li>
              <li>
                <a href="#" class="nav-link" id="menu_covid" onclick="activeMenu('covid')">
                  Covid 19
                </a>
              </li>
              <li>
                <a href="#" class="nav-link">
                  Customers
                </a>
              </li>
            </ul>
            <hr>
            <div class="dropdown">
              <a href="#" class="d-flex align-items-center text-white text-decoration-none">
                <img src="https://www.fainor.com.br/v2/wp-content/themes/fainor-1/img/logo.png" alt="" width="150" height="75">
                <strong>mdo</strong>
              </a>
            </div>
          </div>
      </div>

      <section class="app col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="default-load" style="display: none;">
            <div class="default-load-box">
                <div class="default-load-box-circle"></div>
                <p class="font-weight-bold color-white">Aguarde, carregando...</p>
            </div>
        </div>

        <?= $v->section("content"); ?>
      </section>
    </div>
  </main>

  <script>
    const url = '<?= url(); ?>'
  </script>
  <script type="text/javascript" src="<?= asset(CONF_PACK_NODE . "/jquery/dist/jquery.min.js")?>"></script>
  <script type="text/javascript" src="<?= theme("/assets/script.js", CONF_VIEW_APP); ?>"></script>

</body>